### ISSUE TITLE
Getting connection error when scraping  bills.

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/scrapers-us-municipal#27]
```bash
pupa update --scrape --fastmode chicago
no pupa_settings on path, using defaults
chicago (scrape)
  bills: {}
Not checking sessions...
16:00:59 INFO pupa: save jurisdiction Chicago City Council as jurisdiction_ocd-jurisdiction-country:us-state:il-place:chicago-council.json
16:00:59 INFO pupa: save organization Chicago City Council as organization_81654f1c-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Clerk as post_8165f606-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Mayor as post_816691b0-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 1 as post_816747cc-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 2 as post_816801b2-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 3 as post_8168162a-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 4 as post_81681c10-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 5 as post_8168219c-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 6 as post_81682746-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 7 as post_81682c6e-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 8 as post_816831a0-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 9 as post_816836be-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 10 as post_81683bbe-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 11 as post_816840d2-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 12 as post_8168460e-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 13 as post_81684b18-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 14 as post_8168502c-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 15 as post_81685586-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 16 as post_81685ac2-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 17 as post_81685fd6-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 18 as post_81686558-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 19 as post_81686a62-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 20 as post_81686f6c-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 21 as post_81687480-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 22 as post_81687ade-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 23 as post_8168807e-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 24 as post_81688588-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 25 as post_81688b00-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 26 as post_81689014-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 27 as post_816896e0-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 28 as post_81689c44-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 29 as post_8168a162-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 30 as post_8168a9aa-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 31 as post_8168ae0a-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 32 as post_8168b242-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 33 as post_8168b68e-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 34 as post_8168bd78-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 35 as post_8168c200-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 36 as post_8168c642-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 37 as post_8168ca70-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 38 as post_8168ce9e-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 39 as post_8168d2b8-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 40 as post_8168d722-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 41 as post_8168db5a-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 42 as post_8168df74-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 43 as post_8168e46a-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 44 as post_8168e8ac-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 45 as post_8168ecda-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 46 as post_8168f112-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 47 as post_8168f536-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 48 as post_8168f964-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 49 as post_8168fd92-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save post Ward 50 as post_816901c0-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO pupa: save organization Democrats as organization_816f148e-ed20-11e4-b79e-0024d703f52c.json
16:00:59 INFO scrapelib: GET - https://chicago.legistar.com/Legislation.aspx
16:00:59 INFO scrapelib: POST - https://chicago.legistar.com/Legislation.aspx
Traceback (most recent call last):
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1139, in getresponse
    raise ResponseNotReady(self.__state)
http.client.ResponseNotReady: Request-sent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1139, in getresponse
    raise ResponseNotReady(self.__state)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ResponseNotReady('Request-sent',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fgregg/public/municipal-scrapers-us/.env/bin/pupa", line 9, in <module>
    load_entry_point('pupa==0.4.1', 'console_scripts', 'pupa')()
  File "/home/fgregg/public/municipal-scrapers-us/.env/src/pupa/pupa/cli/__main__.py", line 71, in main
    subcommands[args.subcommand].handle(args, other)
  File "/home/fgregg/public/municipal-scrapers-us/.env/src/pupa/pupa/cli/commands/update.py", line 224, in handle
    report['scrape'] = self.do_scrape(juris, args, scrapers)
  File "/home/fgregg/public/municipal-scrapers-us/.env/src/pupa/pupa/cli/commands/update.py", line 123, in do_scrape
    report[scraper_name] = scraper.do_scrape(**scrape_args)
  File "/home/fgregg/public/municipal-scrapers-us/.env/src/pupa/pupa/scrape/base.py", line 102, in do_scrape
    for obj in self.scrape(**kwargs) or []:
  File "/home/fgregg/public/municipal-scrapers-us/chicago/bills.py", line 89, in scrape
    for i, page in enumerate(self.searchLegislation()) :
  File "/home/fgregg/public/municipal-scrapers-us/chicago/legistar.py", line 24, in pages
    page = self.lxmlize(url, payload)
  File "/home/fgregg/public/municipal-scrapers-us/chicago/legistar.py", line 16, in lxmlize
    entry = self.post(url, payload).text
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/scrapelib/__init__.py", line 270, in request
    **kwargs)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/scrapelib/cache.py", line 66, in request
    resp = super(CachingSession, self).request(method, url, **kwargs)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/scrapelib/__init__.py", line 92, in request
    return super(ThrottledSession, self).request(method, url, **kwargs)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/scrapelib/__init__.py", line 177, in request
    raise exception_raised
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/scrapelib/__init__.py", line 157, in request
    resp = super(RetrySession, self).request(method, url, **kwargs)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/sessions.py", line 594, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/sessions.py", line 196, in resolve_redirects
    **adapter_kwargs
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/fgregg/public/municipal-scrapers-us/.env/lib/python3.4/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ResponseNotReady('Request-sent',))
```

**Comment by fgregg** [comment]
Only happens with --fastmode argument flag

**Comment by fgregg** [comment]
The "TypeError: getresponse() got an unexpected keyword argument 'buffering'" is a red herring: https://github.com/kennethreitz/requests/issues/1289#issuecomment-31294851

**Comment by fgregg** [comment]
Okay, fixed this by deleting a cached file.
